apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::515879578787:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-zQzh9nLDOsZa
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::515879578787:user/suresh
      username: suresh    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-31T15:29:26Z"
  name: aws-auth
  namespace: kube-system
 
  uid: 664f33fb-4eee-491a-98b7-8536211a8905
